apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8stest           # deployment 名称
  namespace:
spec:
  minReadySeconds: 5      # pod启动后等待5s后提供外部服务，防止服务未启动
  strategy:               # 策略
    type: RollingUpdate   # 支持滚动更新设置
    rollingUpdate:
      maxSurge: 1         # 启动一个新的pod后 才删除 一个pod
      maxUnavailable: 1   # 当maxSurge不为0时，该值也不能为0，最好和maxSurge保持一致
  selector:               # 标签选择
    matchLabels:
      app: jalcge         # #选择label：app=jalcge的容器生成pod实例
  replicas: 1             # 副本数量
  template:
    metadata:
      labels:
        app: jalcge
    spec:
      containers:
        - name: jalcge
          image: jalcge/k8s:latest
          args:                # 给容器传参数方法 command: ["1.0"] 和 args
            - '1.0'
          imagePullPolicy: Always  # Always：总是拉取远程仓库镜像 IfNotPresent：默认值,本地有就不拉取  Never：只使用本地镜像不拉取
          ports:
            - containerPort: 8080  # 容器的开放端口
